services:
  - type: web
    name: espocrm
    env: php
    region: oregon
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t public"
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://espouser:J3q7c9HABfyDwv6GnGKC1zYeKZEuyPyH@dpg-d4l3dcbe5dus73fi6vd0-a/espocrm_yf42"
